CARDS = [
    {
        "id": 1,
        "category": "Deepening Understanding",
        "tone": "Low & Honest Time Travel",
        "text": "Think of a quiet disappointment about us last month. Whisper it in 5 words. Partner says only 'I hear that.' Then switch.",
    },
    {
        "id": 2,
        "category": "Deepening Understanding",
        "tone": "Straight Up Sex",
        "text": "Tell your partner: 'The thing I most want you to do to my body that I've never asked for is ______.' No explanation, just the sentence.",
    },
    {
        "id": 3,
        "category": "Deepening Understanding",
        "tone": "Sweet & Sentimental",
        "text": "What's a moment you felt completely seen by me - even if I didn't realize it at the time?",
    },
    {
        "id": 4,
        "category": "Intimate Dares & Play",
        "tone": "Low & Honest Time Travel",
        "text": "Place your hand on their sternum. Say: 'I'm going to press harder for 3 seconds. Tap my wrist to stop.' If they don't, kiss the spot.",
    },
    {
        "id": 5,
        "category": "Intimate Dares & Play",
        "tone": "Seductive & Bold",
        "text": "Pin your partner against the wall. Kiss them once, pull back, and say 'Your move.'",
    },
    {
        "id": 6,
        "category": "Shared Adventures (Mini)",
        "tone": "Straight Up Sex",
        "text": "Flip a coin. Heads = you go down on them for 60 seconds. Tails = they go down on you. No talking during.",
    },
    {
        "id": 7,
        "category": "Shared Adventures (Mini)",
        "tone": "Sweet & Sentimental",
        "text": "Invent a two-part hand squeeze: one squeeze = 'I'm here,' two = 'I like you,' three = 'I love you.' Send messages without speaking.",
    },
    {
        "id": 8,
        "category": "Deepening Understanding",
        "tone": "Low & Honest Time Travel",
        "text": "Ask: 'What's something you've changed your mind about since we met - not about us, about yourself?' Answer with one memory.",
    },
    {
        "id": 9,
        "category": "Playful Time Travel",
        "tone": "Seductive & Bold",
        "text": "Fast-forward to tomorrow morning. Whisper what you'll be thinking about when you first see me naked. Then add: 'So take off one thing now.'",
    },
    {
        "id": 10,
        "category": "Intimate Dares & Play",
        "tone": "Straight Up Sex",
        "text": "Take your partner's hand and put it directly on your cock or clit. Say 'Touch me exactly like this for 10 seconds.' Then stop.",
    },
    {
        "id": 11,
        "category": "Playful Time Travel",
        "tone": "Sweet & Sentimental",
        "text": "Think back to the moment you knew you were falling for me. Describe the exact light, sound, or smell. Then say 'That's still here.'",
    },
    {
        "id": 12,
        "category": "Shared Adventures (Mini)",
        "tone": "Low & Honest Time Travel",
        "text": "Sit facing each other, knees touching. For 90 seconds, take turns naming one real sensation you feel right now (e.g., 'my heel is cold'). No interpretations.",
    },
    {
        "id": 13,
        "category": "Deepening Understanding",
        "tone": "Seductive & Bold",
        "text": "What's a secret desire you've never said aloud because you thought I'd judge you? Whisper it. I'll whisper back 'hot' or 'later.'",
    },
    {
        "id": 14,
        "category": "Playful Time Travel",
        "tone": "Straight Up Sex",
        "text": "Think of the best orgasm you've ever had with me. Whisper where we were and what position. Then say 'Let's try that again in 10 minutes.'",
    },
    {
        "id": 15,
        "category": "Intimate Dares & Play",
        "tone": "Sweet & Sentimental",
        "text": "Hold your partner's hand and kiss each fingertip slowly. After each kiss, say one thing you admire about them.",
    },
    {
        "id": 16,
        "category": "Playful Time Travel",
        "tone": "Low & Honest Time Travel",
        "text": "Think back to a boring Tuesday night last year. Whisper one exact detail that made you feel safe. Then say 'That still counts.'",
    },
    {
        "id": 17,
        "category": "Shared Adventures (Mini)",
        "tone": "Seductive & Bold",
        "text": "Set a 30-second timer. Make your partner blush without touching them. Win = they owe you a 15-second lap dance. Lose = you owe a foot rub.",
    },
    {
        "id": 18,
        "category": "Deepening Understanding",
        "tone": "Straight Up Sex",
        "text": "Ask: 'On a scale of 1-10, how horny were you this morning? What would have made it a 10?' Answer honestly.",
    },
    {
        "id": 19,
        "category": "Deepening Understanding",
        "tone": "Sweet & Sentimental",
        "text": "If our love story were a song, what would the title be? Hum two bars.",
    },
    {
        "id": 20,
        "category": "Intimate Dares & Play",
        "tone": "Low & Honest Time Travel",
        "text": "Whisper: 'The first time you made a sound I'd never heard before - do it again. Just once.' Then wait in silence.",
    },
    {
        "id": 21,
        "category": "Intimate Dares & Play",
        "tone": "Seductive & Bold",
        "text": "Blindfold your partner. Trace a line from their knee to their inner thigh using only your nose.",
    },
    {
        "id": 22,
        "category": "Shared Adventures (Mini)",
        "tone": "Straight Up Sex",
        "text": "Set a 2-minute timer. You can only communicate by drawing one finger on each other's back. Try to agree on: missionary, doggy, or cowgirl.",
    },
    {
        "id": 23,
        "category": "Shared Adventures (Mini)",
        "tone": "Sweet & Sentimental",
        "text": "Both close your eyes. Partner guides your hand to three surfaces in the room. Guess each. Wrong guess = kiss on the hand.",
    },
    {
        "id": 24,
        "category": "Deepening Understanding",
        "tone": "Low & Honest Time Travel",
        "text": "Recall a moment last year when you wanted to cry but didn't. Whisper where you were. Partner says 'I wish I'd been there.'",
    },
    {
        "id": 25,
        "category": "Playful Time Travel",
        "tone": "Seductive & Bold",
        "text": "Re-create the first time you got turned on by your partner - but add one thing you wish you'd done then but were too shy.",
    },
    {
        "id": 26,
        "category": "Intimate Dares & Play",
        "tone": "Straight Up Sex",
        "text": "Tell your partner: 'I want you to fuck me from behind tonight. Yes or no right now?' No means switch to something else.",
    },
    {
        "id": 27,
        "category": "Intimate Dares & Play",
        "tone": "Sweet & Sentimental",
        "text": "Dance together for one song with your foreheads touching. No talking.",
    },
    {
        "id": 28,
        "category": "Shared Adventures (Mini)",
        "tone": "Low & Honest Time Travel",
        "text": "Both lie on the floor. Take turns saying one thing you'd like to do to the other's body that's slightly rude (e.g., 'blow a raspberry on your stomach'). Then do it for 2 seconds.",
    },
    {
        "id": 29,
        "category": "Deepening Understanding",
        "tone": "Seductive & Bold",
        "text": "Tell me one way I've disappointed you in bed. Then tell me one way I've exceeded your expectations.",
    },
    {
        "id": 30,
        "category": "Playful Time Travel",
        "tone": "Straight Up Sex",
        "text": "Fast-forward to tonight after we finish. Whisper one thing you'll be glad we did - and one thing you'll wish we'd done longer.",
    },
    {
        "id": 31,
        "category": "Playful Time Travel",
        "tone": "Sweet & Sentimental",
        "text": "Write a 10-word postcard from 'you five years ago' to 'you tonight.' Read it aloud.",
    },
    {
        "id": 32,
        "category": "Intimate Dares & Play",
        "tone": "Low & Honest Time Travel",
        "text": "Lean close and say: 'Remember the first time we kissed in the dark? Do that again - same pressure, same tilt of the head.'",
    },
    {
        "id": 33,
        "category": "Shared Adventures (Mini)",
        "tone": "Seductive & Bold",
        "text": "Trade one piece of clothing. Now make two drinks wearing each other's item.",
    },
    {
        "id": 34,
        "category": "Deepening Understanding",
        "tone": "Straight Up Sex",
        "text": "Say: 'The word I want to hear you say when you come tonight is ______.' It can be anything - a name, a sound, a curse.",
    },
    {
        "id": 35,
        "category": "Deepening Understanding",
        "tone": "Sweet & Sentimental",
        "text": "What's something you learned about love from your parents that you're glad we don't do?",
    },
    {
        "id": 36,
        "category": "Playful Time Travel",
        "tone": "Low & Honest Time Travel",
        "text": "Say: 'In five years, we'll have forgotten tonight unless we do this.' Lightly tap each other's forehead three times. 'Now we won't forget.'",
    },
    {
        "id": 37,
        "category": "Intimate Dares & Play",
        "tone": "Seductive & Bold",
        "text": "Unbutton your partner's shirt using only your teeth. Stop after each button to exhale on their skin.",
    },
    {
        "id": 38,
        "category": "Intimate Dares & Play",
        "tone": "Straight Up Sex",
        "text": "Lick your palm. Then stroke your partner's shaft or vulva once, slowly. Say 'That's a preview.' Then stop.",
    },
    {
        "id": 39,
        "category": "Shared Adventures (Mini)",
        "tone": "Sweet & Sentimental",
        "text": "Make a fort out of blankets. Inside, take turns saying 'One thing I'd save if the house were on fire besides you.'",
    },
    {
        "id": 40,
        "category": "Deepening Understanding",
        "tone": "Low & Honest Time Travel",
        "text": "Say: 'One thing I used to believe about relationships that you proved wrong is ______.' Then name the opposite belief you hold now.",
    },
    {
        "id": 41,
        "category": "Playful Time Travel",
        "tone": "Seductive & Bold",
        "text": "Go back to our first kiss. Kiss them exactly the same way - then pull back and say 'Now let me show you how I kiss you now.' Do it differently.",
    },
    {
        "id": 42,
        "category": "Shared Adventures (Mini)",
        "tone": "Straight Up Sex",
        "text": "Both sit on the floor facing away from each other. Take turns naming one sexual act you want to do later. No response, just listing.",
    },
    {
        "id": 43,
        "category": "Intimate Dares & Play",
        "tone": "Sweet & Sentimental",
        "text": "Trace the outline of your partner's face with your eyes closed. Guess what expression they're making.",
    },
    {
        "id": 44,
        "category": "Shared Adventures (Mini)",
        "tone": "Low & Honest Time Travel",
        "text": "Set a timer for 3 minutes. Without speaking, try to both stand up at the same time from sitting cross-legged. Laughing is allowed.",
    },
    {
        "id": 45,
        "category": "Deepening Understanding",
        "tone": "Seductive & Bold",
        "text": "If you could make me beg for anything tonight, what would it be? Describe the scene in two sentences.",
    },
    {
        "id": 46,
        "category": "Playful Time Travel",
        "tone": "Straight Up Sex",
        "text": "Imagine we're having sex five years from now. Whisper one new thing you hope we've added by then.",
    },
    {
        "id": 47,
        "category": "Playful Time Travel",
        "tone": "Sweet & Sentimental",
        "text": "If we could relive any ordinary Tuesday from last year, which one would it be? Describe one boring detail.",
    },
    {
        "id": 48,
        "category": "Intimate Dares & Play",
        "tone": "Low & Honest Time Travel",
        "text": "Put your hand on their thigh. Say: 'In 10 seconds, I'll move it two inches higher. Say \"wait\" if you need more time.' Count down silently.",
    },
    {
        "id": 49,
        "category": "Shared Adventures (Mini)",
        "tone": "Seductive & Bold",
        "text": "Both stand up. You can only move when your partner says 'green.' Freeze on 'red.' Try to undress each other using only voice commands.",
    },
    {
        "id": 50,
        "category": "Intimate Dares & Play",
        "tone": "Straight Up Sex",
        "text": "Ask: 'Fingers or tongue first?' Whatever they say, do it for 15 seconds - then ask again.",
    },
    {
        "id": 51,
        "category": "Deepening Understanding",
        "tone": "Sweet & Sentimental",
        "text": "Tell me about a time this month when you felt lonely even though I was nearby. No fixing - just 'thank you' from me.",
    },
    {
        "id": 52,
        "category": "Deepening Understanding",
        "tone": "Low & Honest Time Travel",
        "text": "Think of a time you felt proud of yourself that you never told me about. Whisper the age you were. Partner says 'That still lives in you.'",
    },
    {
        "id": 53,
        "category": "Intimate Dares & Play",
        "tone": "Seductive & Bold",
        "text": "Whisper 'I want to ruin you later' into their ear. Then walk away and don't touch them for 2 minutes.",
    },
    {
        "id": 54,
        "category": "Deepening Understanding",
        "tone": "Straight Up Sex",
        "text": "Ask: 'What position makes you feel the most wanted by me? Why that one?'",
    },
    {
        "id": 55,
        "category": "Shared Adventures (Mini)",
        "tone": "Sweet & Sentimental",
        "text": "Cook something simple together (toast, popcorn). You can only communicate by humming. First laugh loses.",
    },
    {
        "id": 56,
        "category": "Playful Time Travel",
        "tone": "Low & Honest Time Travel",
        "text": "Both close your eyes. Say 'I want future us to know that tonight we felt ______.' Fill in with one word.",
    },
    {
        "id": 57,
        "category": "Playful Time Travel",
        "tone": "Seductive & Bold",
        "text": "Imagine we're 80 years old. Whisper what you'll still want me to do to your body then. Then do it once, gently.",
    },
    {
        "id": 58,
        "category": "Shared Adventures (Mini)",
        "tone": "Straight Up Sex",
        "text": "Put a condom on a banana or a cucumber together using only one hand each. Fastest time wins a 30-second naked cuddle.",
    },
    {
        "id": 59,
        "category": "Intimate Dares & Play",
        "tone": "Sweet & Sentimental",
        "text": "Give your partner a back rub using only the backs of your hands - no palms.",
    },
    {
        "id": 60,
        "category": "Shared Adventures (Mini)",
        "tone": "Low & Honest Time Travel",
        "text": "Close your eyes. Your partner will put one of their hands on top of yours. Without peeking, draw what you feel on a piece of paper.",
    },
    {
        "id": 61,
        "category": "Deepening Understanding",
        "tone": "Seductive & Bold",
        "text": "What's a non-sexual thing I do that secretly turns you on? Be specific.",
    },
    {
        "id": 62,
        "category": "Playful Time Travel",
        "tone": "Straight Up Sex",
        "text": "Recall the first time you masturbated thinking of me. Whisper what I was wearing in that memory.",
    },
]


CARDS_BY_ID = {card["id"]: card for card in CARDS}
